const express = require('express')
const passport = require('passport')
const upload = require('../middleware/upload')
const controller = require('../controllers/table')
const router = express.Router()

router.post('/', passport.authenticate('jwt', {session: false}), upload.single('image'), controller.create)
router.patch('/:id', passport.authenticate('jwt', {session: false}), upload.single('image'), controller.update)
router.get('/', passport.authenticate('jwt', {session: false}), controller.getAll)
router.delete('/:id', passport.authenticate('jwt', {session: false}), controller.remove)